version: '3.6'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=employee_ass
        - POSTGRES_USER=eswarpriya
        - POSTGRES_PASSWORD=eswarpriya@3
    ports:
      - 5433:5432
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: {}